[toolchain]
# cargo --version
# cargo 1.73.0-nightly (d78bbf4bd 2023-08-03)
# rustup run nightly rustc --version
# rustc 1.73.0-nightly (474709a9a 2023-08-03)
channel = "nightly"
components = ["rust-src", "llvm-tools", "rustfmt", "clippy"]
profile = "minimal"
targets = ["riscv32imac-unknown-none-elf"]
