[build]
target = "riscv32imac-unknown-none-elf"


[target.riscv32imac-unknown-none-elf]
runner = """
qemu-system-riscv32 -machine virt -bios default -nographic -serial mon:stdio --no-reboot \
    -d unimp,guest_errors,int,cpu_reset -D qemu.log \
    -kernel target/riscv32imac-unknown-none-elf/debug/os
"""

# """
# qemu-system-riscv32 -machine virt -bios default -nographic -serial mon:stdio --no-reboot \
#     -d unimp,guest_errors,int,cpu_reset -D qemu.log \
#     -drive id=drive0,file=disk.tar,format=raw \
#     -device virtio-blk-device,drive=drive0,bus=virtio-mmio-bus.0 \
#     -kernel target/riscv32imac-unknown-none-elf/debug/os
# """

[alias]
# -r is release
# Dump disassemble
dmp = "objdump --bin os -- -d"
dmp-r = "objdump --bin os --release -- -d"
# Show symbol mapping address
sym = "nm --bin os"
sym-r = "nm --bin os --release"
