[build]
target = "riscv32imac-unknown-none-elf"


[target.riscv32imac-unknown-none-elf]
rustflags = ["-Clink-arg=-Tsrc/kernel/kernel.ld", "-Cforce-frame-pointers=yes"]
runner = """
qemu-system-riscv32 -machine virt -bios default -nographic -serial mon:stdio --no-reboot \
    -kernel target/riscv32imac-unknown-none-elf/debug/os
"""

# """
# qemu-system-riscv32 -machine virt -bios default -nographic -serial mon:stdio --no-reboot \
#     -d unimp,guest_errors,int,cpu_reset -D qemu.log \
#     -drive id=drive0,file=disk.tar,format=raw \
#     -device virtio-blk-device,drive=drive0,bus=virtio-mmio-bus.0 \
#     -kernel target/riscv32imac-unknown-none-elf/debug/os
# """

[alias]
disasm = "objdump --bin os --release -- -d"
nm = "nm --bin os --release"                # show symbol mapping address
